using System;
using System.Globalization;
using System.IO;
using QuizGenAI.DTOs;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace QuizGenAI.Services
{
    public class ResultPdfExportService
    {
        private const string BrandGreen = "#145E45";
        private const string BrandGreenSoft = "#EAF4EF";
        private const string BrandGold = "#D4AF37";
        private const string Border = "#D9E1DA";
        private const string TextPrimary = "#12211A";
        private const string TextMuted = "#5F6E67";

        public void Export(StudentAttemptSummaryDto summary, string outputPath)
        {
            if (summary == null)
            {
                throw new ArgumentNullException("summary");
            }

            if (string.IsNullOrWhiteSpace(outputPath))
            {
                throw new ArgumentException("Output path is required.", "outputPath");
            }

            QuestPDF.Settings.License = LicenseType.Community;

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(26);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(10).FontColor(TextPrimary));

                    page.Content().Column(column =>
                    {
                        column.Spacing(18);
                        column.Item().Element(x => ComposeHeader(x, summary));
                        column.Item().Element(x => ComposeScoreHero(x, summary));
                        column.Item().Element(x => ComposeMetrics(x, summary));
                        column.Item().Element(x => ComposeRecommendations(x, summary));
                    });

                    page.Footer().AlignRight().Text(x =>
                    {
                        x.Span("Generated by QuizGen AI on ").FontColor(TextMuted);
                        x.Span(DateTime.Now.ToString("MMM d, yyyy h:mm tt", CultureInfo.InvariantCulture)).SemiBold();
                    });
                });
            }).GeneratePdf(outputPath);
        }

        private static void ComposeHeader(IContainer container, StudentAttemptSummaryDto summary)
        {
            container.Column(column =>
            {
                column.Spacing(6);
                column.Item().Text("QUIZ RESULT SUMMARY").SemiBold().FontSize(10).FontColor(BrandGreen);
                column.Item().Text(summary.QuizTitle).Bold().FontSize(24).FontColor(TextPrimary);
                column.Item().Text(string.Format(
                    "{0} | {1} | Student: {2}",
                    Safe(summary.SubjectName),
                    Safe(summary.Topic),
                    Safe(summary.StudentName)))
                    .FontSize(11)
                    .FontColor(TextMuted);
            });
        }

        private static void ComposeScoreHero(IContainer container, StudentAttemptSummaryDto summary)
        {
            container
                .Background(BrandGreen)
                .Border(1)
                .BorderColor(BrandGold)
                .CornerRadius(18)
                .Padding(22)
                .Column(column =>
                {
                    column.Spacing(10);
                    column.Item().AlignCenter().Text(GetEffortLabel(summary.ScorePercentage))
                        .SemiBold()
                        .FontSize(12)
                        .FontColor(BrandGold);

                    column.Item().AlignCenter().Text(string.Format(CultureInfo.InvariantCulture, "{0:0.#}%", summary.ScorePercentage))
                        .Bold()
                        .FontSize(34)
                        .FontColor(Colors.White);

                    column.Item().AlignCenter().Text(string.Format(
                        "{0} of {1} correct",
                        summary.CorrectAnswers,
                        summary.TotalQuestions))
                        .FontSize(13)
                        .FontColor(Colors.White);

                    column.Item().AlignCenter().Text(string.Format(
                        "Submitted {0} | Time spent {1}",
                        Safe(summary.SubmittedAtDisplay),
                        Safe(summary.TimeSpentDisplay)))
                        .FontSize(10)
                        .FontColor("#D7E7DE");
                });
        }

        private static void ComposeMetrics(IContainer container, StudentAttemptSummaryDto summary)
        {
            container.Row(row =>
            {
                row.Spacing(12);
                row.RelativeItem().Element(x => ComposeMetricCard(x, "Correct", summary.CorrectAnswers.ToString(CultureInfo.InvariantCulture), BrandGreen));
                row.RelativeItem().Element(x => ComposeMetricCard(x, "Wrong", summary.WrongAnswers.ToString(CultureInfo.InvariantCulture), "#A94442"));
                row.RelativeItem().Element(x => ComposeMetricCard(x, "Unanswered", summary.UnansweredQuestions.ToString(CultureInfo.InvariantCulture), BrandGold));
            });
        }

        private static void ComposeMetricCard(IContainer container, string label, string value, string accentColor)
        {
            container
                .Background(BrandGreenSoft)
                .Border(1)
                .BorderColor(Border)
                .CornerRadius(14)
                .Padding(16)
                .Column(column =>
                {
                    column.Spacing(4);
                    column.Item().Text(label).SemiBold().FontSize(10).FontColor(TextMuted);
                    column.Item().Text(value).Bold().FontSize(22).FontColor(accentColor);
                });
        }

        private static void ComposeRecommendations(IContainer container, StudentAttemptSummaryDto summary)
        {
            container
                .Border(1)
                .BorderColor(Border)
                .CornerRadius(16)
                .Padding(18)
                .Column(column =>
                {
                    column.Spacing(12);
                    column.Item().Text("AI Study Recommendations").Bold().FontSize(18).FontColor(TextPrimary);
                    column.Item().Text(string.Format(
                        "Source: {0}",
                        string.IsNullOrWhiteSpace(summary.RecommendationSourceLabel) ? "Unavailable" : summary.RecommendationSourceLabel))
                        .FontSize(10)
                        .FontColor(TextMuted);

                    if (summary.Recommendations == null || summary.Recommendations.Count == 0)
                    {
                        column.Item().Text("No recommendations are available for this attempt yet.")
                            .FontSize(10)
                            .FontColor(TextMuted);
                        return;
                    }

                    foreach (var recommendation in summary.Recommendations)
                    {
                        column.Item()
                            .Background("#FBFCFA")
                            .Border(1)
                            .BorderColor(Border)
                            .CornerRadius(12)
                            .Padding(14)
                            .Column(itemColumn =>
                            {
                                itemColumn.Spacing(6);
                                itemColumn.Item().Text(Safe(recommendation.Title)).SemiBold().FontSize(12).FontColor(TextPrimary);
                                itemColumn.Item().Text(Safe(recommendation.Description)).FontSize(10).FontColor(TextMuted);
                            });
                    }
                });
        }

        private static string GetEffortLabel(double score)
        {
            if (score >= 85)
            {
                return "EXCELLENT WORK";
            }

            if (score >= 60)
            {
                return "GOOD EFFORT";
            }

            return "KEEP PRACTICING";
        }

        private static string Safe(string value)
        {
            return string.IsNullOrWhiteSpace(value) ? "N/A" : value.Trim();
        }

        public static string BuildDefaultFileName(StudentAttemptSummaryDto summary)
        {
            var quizTitle = Safe(summary != null ? summary.QuizTitle : null);
            return string.Format(
                CultureInfo.InvariantCulture,
                "{0}-Result-{1:yyyyMMdd-HHmm}.pdf",
                SanitizeFileNamePart(quizTitle),
                DateTime.Now);
        }

        private static string SanitizeFileNamePart(string value)
        {
            var invalidChars = Path.GetInvalidFileNameChars();
            var buffer = value.ToCharArray();

            for (var i = 0; i < buffer.Length; i++)
            {
                if (Array.IndexOf(invalidChars, buffer[i]) >= 0)
                {
                    buffer[i] = '-';
                }
            }

            return new string(buffer).Replace(' ', '-');
        }
    }
}
